"""create links table

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-29 13:51:51.947233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('long_url', sa.Text(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('click_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_links_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_links')),
    sa.UniqueConstraint('code', name=op.f('uq_links_code'))
    )
    op.create_index('ix_links_purge_candidates', 'links', ['last_clicked_at', 'created_at'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index('ix_links_user_id', 'links', ['user_id'], unique=False, postgresql_where=sa.text('user_id IS NOT NULL'))
    # ### end Alembic commands ###
    op.execute(
        "CREATE TRIGGER trg_links_set_updated_at BEFORE UPDATE ON links "
        "FOR EACH ROW EXECUTE FUNCTION set_updated_at()"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER trg_links_set_updated_at ON links")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_links_user_id', table_name='links', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_index('ix_links_purge_candidates', table_name='links', postgresql_where=sa.text('is_active = true'))
    op.drop_table('links')
    # ### end Alembic commands ###
